FROM grafana/grafana:12.3

USER root

# Pre-install plugins at build time (faster startup)
RUN grafana-cli plugins install volkovlabs-echarts-panel && \
    grafana-cli plugins install marcusolsson-dynamictext-panel

USER grafana